title: Sai Nikhil Kunapareddy
#logo: /path/
description: "Graduate Student | MS in Data Science | Former Senior Computational Engineer | Machine Learning"
show_downloads: false
theme: jekyll-theme-minimal
