title: Sai Nikhil Kunapareddy
logo: /assets/head_shot.jpg
description: "Master's in Data Science \n Former Senior Computational Engineer \n Machine Learning Enthusiast"
show_downloads: false
theme: jekyll-theme-minimal
