title: Sai Nikhil Kunapareddy
logo: /assets/head_shot.jpg
description: "Master's in Data Science | Former Senior Computational Engineer | Machine Learning Enthusiast"
show_downloads: false
theme: jekyll-theme-minimal
